// Generated by Emscripten (--emit-tsd) in the tetris repo: build/wasm/wasm/tetris.d.ts
// TypeScript bindings for emscripten-generated code.  Automatically generated at compile time.
interface WasmModule {
}

export interface ClassHandle {
  isAliasOf(other: ClassHandle): boolean;
  delete(): void;
  deleteLater(): this;
  isDeleted(): boolean;
  // @ts-ignore - If targeting lower than ESNext, this symbol might not exist.
  [Symbol.dispose](): void;
  clone(): this;
}
export interface ActionValue<T extends number> {
  value: T;
}
export type Action = ActionValue<0>|ActionValue<1>|ActionValue<2>|ActionValue<3>|ActionValue<4>|ActionValue<5>;

export interface Game extends ClassHandle {
  readonly width: number;
  readonly height: number;
  readonly score: number;
  readonly lines: number;
  readonly level: number;
  readonly over: boolean;
  readonly gravityIntervalMs: number;
  readonly currentShape: number;
  readonly nextShape: number;
  apply(_0: Action): void;
  tick(): void;
  board(): any;
  currentCells(): any;
  ghostCells(): any;
  nextCells(): any;
}

interface EmbindModule {
  Action: {MoveLeft: ActionValue<0>, MoveRight: ActionValue<1>, RotateClockwise: ActionValue<2>, RotateCounterClockwise: ActionValue<3>, SoftDrop: ActionValue<4>, HardDrop: ActionValue<5>};
  Game: {
    new(_0: number): Game;
  };
}

export type MainModule = WasmModule & EmbindModule;
export default function MainModuleFactory (options?: unknown): Promise<MainModule>;
