name: refresh resume
on:
  push:
    branches:
      - master

jobs:
  build-resume:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/akdev1l/resume-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    steps:
      - name: check out repository code
        uses: actions/checkout@v2

      - name: render resume
        run: make

      - name: push to output branch
        run: |
          git config --global user.name 'resume-builder'
          git config --global user.email 'resume-builder@akdev.xyz'
          git checkout -b output
          git add -f docs/main.pdf
          git rm -rf .github/workflows
          git commit -m 'ci/cd: generated output pdf'
          git push -fu origin output

      - uses: actions/upload-artifact@v2
        with:
          name: resume-latest.pdf
          path: ./docs/main.pdf
