name: refresh resume
on:
  push:
    branches:
      - master

jobs:
  build-resume:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          dnf install -y \
            /usr/bin/xelatex \
            texlive-parskip \
            make \
            lilypond-texgyre-heros-fonts \
            texlive-textpos \
            texlive-biblatex \
            texlive-progressbar \
            texlive-firstaid \
            lato-fonts \
            texlive-lato \
            texlive-tex-gyre
          make
      - name: push to output branch
        run: |
          git config --global user.name 'resume-builder'
          git config --global user.email 'resume-builder@akdev.xyz'
          git checkout output
          git commit -am 'ci/cd: generated output pdf'
          git push
      - uses: actions/upload-artifact@v2
        with:
          name: resume-latest.pdf
          path: ./docs/main.pdf
