name: refresh resume
on:
  push:
    branches:
      - master

jobs:
  build-resume:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: install build dependencies
        run: |
          dnf install -y \
            /usr/bin/xelatex \
            lilypond-texgyre-heros-fonts \
            lato-fonts \
            make \
            git \
            texlive-lato \
            texlive-tex-gyre \
            texlive-parskip \
            texlive-textpos \
            texlive-biblatex \
            texlive-progressbar \
            texlive-firstaid
      - name: check out repository code
        uses: actions/checkout@v2
      - name: render resume
        run: make
      - name: push to output branch
        run: |
          pwd
          ls *
          git config --global user.name 'resume-builder'
          git config --global user.email 'resume-builder@akdev.xyz'
          git checkout -b output
          git commit -m 'ci/cd: generated output pdf'  -- ./docs/main.pdf
          git push -fu origin output
      - uses: actions/upload-artifact@v2
        with:
          name: resume-latest.pdf
          path: ./docs/main.pdf
