name: build web distribution
on:
  push:
    branches:
      - master
    paths:
      - 'web/**'

jobs:
  builr-resume-web:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/akdev1l/resumes/resume-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    steps:
      - name: check out repository code
        uses: actions/checkout@v2

      - name: build web distribution
        run: make resume-web

      - name: upload resume-web artifact
        uses: actions/upload-artifact@v2
        with:
          name: akdev-resume-web
          path: ./docs/

      - name: configure git and output branch
        run: |
          git config --global user.name 'resume-builder'
          git config --global user.email 'resume-builder@akdev.xyz'
          git checkout -b output

      - name: add build output and clean out gh workflows
        run: |
          git add -f docs/
          git rm -rf .github/workflows

      - name: git push to output branch
        run: |
          git commit -m "ci/cd: generated from commit $(git rev-parse --short "${GITHUB_SHA}")"
          git push -fu origin output

      - uses: actions/upload-artifact@v2
        with:
          name: akdev-resume
          path: ./docs/main.pdf
