on:
  push:
    branches:
      - master
      
name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag: ${{ steps.release-please.outputs.tag_name }}
      upload_url: ${{ steps.release-please.outputs.upload_url }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: node
          package-name: release-please-action

  trigger-cf-build:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.releases_created
    container: 
      image: ghcr.io/akdev1l/resume-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ github.token }}
    permissions:
      contents: write
      packages: write
    steps:
      - name: check out repository code
        uses: actions/checkout@v2
      - name: render resume
        run: make
      - uses: actions/upload-artifact@v2
        with:
          name: akdev-resume
          path: ./docs/main.pdf
      - name: install github CLI
        run: |
          sudo dnf install 'dnf-command(config-manager)' -y
          sudo dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          sudo dnf install gh -y
      - name: upload pdf to release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload \
            ${{ needs.release-please.outputs.tag }} \
            ./docs/main.pdf \
            --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} \
            --clobber
