name: refresh resume
on:
  push:
    branches:
      - master

jobs:
  build-resume:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2

      - name: build resume-builder container
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: akdev1l/resume-builder
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile

      - name: push to container registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/akdev1l
